version: ""

formatter: markdown table

name: terraform-aws-iam-role-cross-account-trusting

content: |-
  # terraform-aws-iam-role-cross-account-trusting

  GitHub: [StratusGrid/terraform-aws-iam-role-cross-account-trusting](https://github.com/StratusGrid/terraform-aws-iam-role-cross-account-trusting)

  This module creates a role that can be assumed by another principal (usually in another account, but could be user or role) to act as that role with permissions from the attached policies.
  
  ### <span style="color:red">NOTE:</span> This is the TRUSTING side. You will still need to create a policy on the TRUSTED side that allows users in that account to assume the role
  
  ## Example usage of the module:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace